/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вхід в систему */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Успішний вхід */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Реєстрація нового користувача */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Користувач успішно зареєстрований */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                409: components["responses"]["ConflictError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вихід з системи */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успішний вихід */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Оновити access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    refresToken?: string;
                };
            };
            requestBody?: never;
            responses: {
                /** @description Access token оновлено успішно */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Отримати профіль поточного користувача */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Профіль користувача */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        /** Оновити профіль користувача */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdateRequest"];
                };
            };
            responses: never;
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Отримати список усіх форм поточного адміністратора */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort?: "createdAt" | "updatedAt" | "title";
                    filter?: string;
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список форм */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FormsList"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
            };
        };
        put?: never;
        /** Створити нову форму */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFormRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/{formId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Отримати форму по ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        post?: never;
        /** Видалити існуючу форму */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Форма успішно видалена */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        options?: never;
        head?: never;
        /** Оновити існуючу форму */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateFormRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        trace?: never;
    };
    "/forms/{formId}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Активувати форму */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        trace?: never;
    };
    "/forms/{formId}/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Опублікувати форму */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        trace?: never;
    };
    "/forms/{formId}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Додати поле до форми */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFieldRequest"];
                };
            };
            responses: {
                /** @description Поле успішно додано */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FieldResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/{formId}/fields/{fieldId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Оновити поле у форми */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                    fieldId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Поле успішно видалено */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        options?: never;
        head?: never;
        /** Оновити поле у форми */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    formId: string;
                    fieldId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateFieldRequest"];
                };
            };
            responses: {
                /** @description Поле успішно оновлено */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FieldResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
        };
        AuthResponse: {
            accessToken: string;
            user: components["schemas"]["User"];
        };
        Error: {
            /** @example Something went wrong */
            message?: string;
            /** @example INTERNAL_ERROR */
            code?: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        UserResponse: {
            /** @example clt1234567890abcdef */
            id?: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email?: string;
            /** @example John */
            firstName?: string | null;
            /** @example Doe */
            lastName?: string | null;
            /** @example https://example.com/avatar.jpg */
            avatarUrl?: string | null;
            preferences?: {
                /** @example uk */
                language?: string;
                /**
                 * @example auto
                 * @enum {string}
                 */
                theme?: "light" | "dark" | "auto";
                /** @example true */
                emailNotifications?: boolean;
            } | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UserUpdateRequest: {
            /** @example John */
            firstName?: string | null;
            /** @example Doe */
            lastName?: string | null;
            /** @example https://example.com/avatar.jpg */
            avatarUrl?: string | null;
            preferences?: {
                /** @example uk */
                language?: string;
                /**
                 * @example auto
                 * @enum {string}
                 */
                theme?: "light" | "dark" | "auto";
                /** @example true */
                emailNotifications?: boolean;
            } | null;
        };
        OptionResponse: {
            id?: string;
            fieldId?: string;
            /** @example option1 */
            optionValue?: string;
            /** @example Варіант 1 */
            optionLabel?: string;
            /** @example 1 */
            sortOrder?: number;
        };
        FieldResponse: {
            id?: string;
            formId?: string;
            /**
             * @example text
             * @enum {string}
             */
            fieldType?: "text" | "email" | "number" | "textarea" | "select" | "radio" | "checkbox" | "date" | "file";
            /** @example Ваше імʼя */
            label?: string;
            /** @example Введіть ваше імʼя */
            placeholder?: string;
            /** @example true */
            isRequired?: boolean;
            /** @example 1 */
            sortOrder?: number;
            validationRules?: Record<string, never>;
            options?: components["schemas"]["OptionResponse"][];
            /** Format: date-time */
            createdAt?: string;
        };
        Form: {
            id: string;
            title: string;
            description?: string | null;
            isActive: boolean;
            isPublic: boolean;
            fields?: components["schemas"]["FieldResponse"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        FormsList: {
            list: components["schemas"]["Form"][];
            total: number;
            totalPages: number;
        };
        CreateFormRequest: {
            title: string;
            description?: string;
        };
        UpdateFormRequest: {
            title?: string;
            description?: string;
        };
        CreateOptionRequest: {
            /** @example option1 */
            optionValue: string;
            /** @example Варіант 1 */
            optionLabel: string;
            /** @example 1 */
            sortOrder: number;
        };
        CreateFieldRequest: {
            /**
             * @example text
             * @enum {string}
             */
            fieldType: "text" | "email" | "number" | "textarea" | "select" | "radio" | "checkbox" | "date" | "file";
            /** @example Ваше імʼя */
            label: string;
            /** @example Введіть ваше імʼя */
            placeholder?: string;
            /** @example true */
            isRequired?: boolean;
            options?: components["schemas"]["CreateOptionRequest"][];
            validationRules?: Record<string, never>;
        };
        UpdateOptionRequest: {
            /** @example option1 */
            optionValue?: string;
            /** @example Варіант 1 */
            optionLabel?: string;
            /** @example 1 */
            sortOrder?: number;
        };
        UpdateFieldRequest: {
            /**
             * @example text
             * @enum {string}
             */
            fieldType?: "text" | "email" | "number" | "textarea" | "select" | "radio" | "checkbox" | "date" | "file";
            /** @example Ваше імʼя */
            label?: string;
            /** @example Введіть ваше імʼя */
            placeholder?: string;
            /** @example true */
            isRequired?: boolean;
            options?: components["schemas"]["UpdateOptionRequest"][];
            validationRules?: Record<string, never>;
        };
    };
    responses: {
        /** @description Помилка валідації */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Неавторизований доступ */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ресурс не знайдено */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Такий користувач вже існує */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
